"""Alterar tamanho das colunas description e resume

Revision ID: 2f41344bf236
Revises: bb2f68d10b96
Create Date: 2025-01-21 08:48:24.245314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f41344bf236'
down_revision: Union[str, None] = 'bb2f68d10b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
