"""nova tabela transcricao

Revision ID: bb2f68d10b96
Revises: 8f087a119358
Create Date: 2025-01-20 18:52:02.667953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2f68d10b96'
down_revision: Union[str, None] = '8f087a119358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('segments', sa.Integer(), nullable=True),
    sa.Column('resume', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcricoes_id'), 'transcricoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcricoes_id'), table_name='transcricoes')
    op.drop_table('transcricoes')
    # ### end Alembic commands ###
